### ISSUE TITLE
Paper problem

### ISSUE THREAD

**Issue by dhx000** [wyf0912/LDDG#1]
I have a question about your paper,The last third line on Page 3:‘’in other words,the rank of matirx is expected to be 1"?

**Comment by wyf0912** [comment]
Hi, sorry for the confusion . In fact, it is a typo. In camera-ready version, we have corrected it. I will also update the arxiv version soon.

 In other words, there exists a dominant eigenvalue capturing the category information of the matrix ![](http://latex.codecogs.com/gif.latex?\\[z_{i_1,c}^1,z_{i_2,c}^2,...,z_{i_K,c}^K]). Therefore, given a sample mini-batch  denoted by $\mathcal{X} = \{x_i^k\}$, we can obtain the corresponding latent features as $\mathcal{Z}$ through a posterior $q(z|x)$ parameterized by an encoder. By further conducting mode-1 flattening $\mathcal{Z}$ as $\mathbf{Z}$\footnote{We assume that the first dimension is associated with sample index.}, our proposed rank regularization can be given as $rank(\mathbf{Z}) = C$,
where $C$ is the number of categories of a specific task.

**Comment by dhx000** [comment]
Thank you very much.

**Comment by wyf0912** [comment]
HI, the version in arxiv has updated
