### ISSUE TITLE
The code for skin lesion classification

### ISSUE THREAD

**Issue by BurningFr** [wyf0912/LDDG#2]
Hi, I find this repo only has the code for spinal cord gray matter segmentation.  Is there any plan to release the code for skin lesion classification in the future?

**Comment by wyf0912** [comment]
Hi, thanks for your interest.  

The code for the skin dataset has not been sorted yet considering that some datasets in the benchmark require additional authorization and purchase. 

I will sort and release the code for that after finishing my current work.
